### PR TITLE
fix: use method signature to allow using functional polymorphism

### PR DESCRIPTION
**Pull request by bmateus**
issue discussed [here](https://github.com/gemstation/gemforge/issues/39)

### CODE REVIEW

**Comment by hiddentao** [comment]
Thanks for the submission!

Just tested this against the https://github.com/gemstation/contracts-foundry repo and got test failures. I think the code might need a bit of tweaking.

**Comment by hiddentao** [comment]
The issue is that funtions which take structs as parameters won't have the correct selectors generated. Doing so would require deconstructing the struct and nested structs and then doing something like:

```solidity
complexFunction((uint256,address,(uint256,bool)))
```

**Comment by hiddentao** [comment]
Merged in #42

**Comment by bmateus** [comment]
thanks!

**Pull request closed without merging**
